### ISSUE TITLE
The database cannot load any data

### ISSUE THREAD

**Issue by Alex-XJK** [Alex-XJK/CS3343_Group6#66]
**Describe the bug**
After I updated to "Merge pull request #59", the whole program failed to start up. When I try to run your latest version program, it throws an unhandled exception called "IllegalStationException", which seems to be caused by the "loadStation()" function in your "Database" class, but as a user, I do not know where it is actually caused, so I attached a screenshot below, hope it will be helpful to you.

**Possible related components**
src/metroSystem.Database#
data/stations_SZ

**To Reproduce**
1.Pull down your latest version after the "Merge pull request #59"
2. Go to 'metroSystem' package
3. Switch to 'Main.java' file
4. Run the program by clicking on "run"
5. See error

**Expected behavior**
The program should be able to run successfully without any difficulties, namely no matter what is the output result, there should be no exception throwing out and the database should be loaded by the system.

**Screenshots**
<img width="960" alt="微信图片_20211105093032" src="https://user-images.githubusercontent.com/63804113/140443992-8163aa70-1a96-44ea-ba81-32fb596295ad.png">

**Desktop**
 - OS: Windows 11
 - IDE: IntelliJ IDEA
 - Version: 2021.2.2
 - JDK 11.0.13

**Additional context**
Personally, I think there may be something wrong inside your database file, maybe a new structure that goes wrong?

**Comment by xz-cs** [comment]
### CONFIRMED
The bug has been confirmed to be reproducible.  
It seems that the newly modified data file format does not match the old data read method well.

**Comment by wliu283** [comment]
### BUGFIX
The structure of the related data files has been adjusted in the latest changes and this issue has been resolved.
