### ISSUE TITLE
Wrong English station name

### ISSUE THREAD

**Issue by xz-cs** [Alex-XJK/CS3343_Group6#70]
**Describe the bug**
In the Hong Kong Train map, "Jordan" is spelled as "Jordon", which results in a NullPointerException.

**Possible related components**
src/userInterface.MTR_eng

**To Reproduce**
1. Launch the main user interface
2. Find the station "Jordon" which is a wrong spelling

**Expected behavior**
It should be "Jordan".

**Screenshots**
![7751635759427_ pic_hd](https://user-images.githubusercontent.com/59300821/140470443-bcf3eac6-3f6c-452c-bfb6-56690d06795f.jpg)

**Environment**
 - OS: All
 - IDE: All
 - Version current
 - JDK/JRE version 17.0.1

**Additional context**
Should be very easy to correct the spelling.

**Comment by Alex-XJK** [comment]
### CONFIRMED
The bug has been confirmed to be reproducible.  
Thank you so much for helping us find this spelling error.

**Comment by Alex-XJK** [comment]
### BUGFIX
The word spelling of the related stations has been adjusted and further checked in the "Pull request #81 ".  
This issue has been resolved now.
