### ISSUE TITLE
Strange responsed shortest route

### ISSUE THREAD

**Issue by Alex-XJK** [Alex-XJK/CS3343_Group6#76]
**Describe the bug**
I was prompted by your system to walk to Shenzhen for a while when I am looking for two mtr stations in Hong Kong, which seemed unreasonable.

**Possible related components**
src/metroSystem.CrtStation#findRoute(int, int)

**To Reproduce**
1. Go to 'Main'
2. Click on 'run'
3. When we search the route from  "Siu Hong" to "Lo Wu" using the "Minimal Station Number"

**Expected behavior**
I think it should promote to me the route which is all located inside HK

**Screenshots**
![微信图片_20211105213953](https://user-images.githubusercontent.com/63804113/140522589-b0b8b450-303a-4b7a-b673-a9181717e258.jpg)

**Environment**
 - OS: Windows
 - IDE: IntelliJ IDEA
 - Version 2021.2.2
 - JDK/JRE version 11.0.13

**Additional context**
Not sure whether this is a bug or a special feature?

**Comment by xz-cs** [comment]
This is normal under "Least time" criteria.

```
Siu Hong --> Lo Wu
Least Time
This route has passed Hong Kong region. Points are: 
[64, 65, 66, 67, 68, 69, 25, 52, 70, 71, 72, 86, 34, 77, 87, 89, 90, 91, 92, 93, 94, 95]
All Stations are: 
[Siu Hong, Tin Shui Wai, Long Ping, Yuen Long, Kam Sheung Road, Tsuen Wan West, Mei Foo, Nam Cheong, Austin, East Tsim Sha Tsui, Hung Hom, Mong Kok East, Kowloon Tong, Tai Wai, Sha Tin, Racecourse, University, Tai Po Market, Tai Wo, Fanling, Sheung Shui, Lo Wu]
```
