### ISSUE TITLE
Some of the key buttons cannot be shown on my screen

### ISSUE THREAD

**Issue by Alex-XJK** [Alex-XJK/CS3343_Group6#82]
**Describe the bug**
The three very important buttons: "Traffic Map(HK)", "Traffic Map(SZ)", and "Find Path" cannot be shown when I maximize the software window to full screen.

**Possible related components**
src/userInterface.Main#main()

**To Reproduce**
1. Download your latest version after "Pull Request #81"
2. Go to your main code
3. Click on run
4. Maximize the promoted UI window to full screen
5. You may lose those buttons

**Expected behavior**
No matter where they are (probably due to your responsive design?), at least I should be able to find those three buttons within the screen.

**Screenshots**
<img width="960" alt="cannot see buttons" src="https://user-images.githubusercontent.com/63804113/140652533-dae37cb6-bdb5-427a-8a19-4cb81754be61.png">

**Environment**
 - OS: windows 11
 - IDE: IntelliJ IDEA
 - Version 2021.1.4
 - JDK/JRE version JDK-11

**Additional context**
By the way, my screen is 1920*1080 in size, with a 60.05Hz refresh rate.

**Comment by Alex-XJK** [comment]
By the way, my screen is 1920*1080 in size, with a 60.05Hz refresh rate.

**Comment by xz-cs** [comment]
Here is what it looks like in iMac (Retina 5K, 27-inch):

<img width="2560" alt="Screen Shot 2021-11-15 at 2 00 44 PM" src="https://user-images.githubusercontent.com/59300821/141730296-a4cc1c98-d5df-4d2c-b0a8-766705279635.png">

The main UI layout looks fine.
