### ISSUE TITLE
Cannot show the result (highlighting edges) correctly when resize the program window

### ISSUE THREAD

**Issue by wliu283** [Alex-XJK/CS3343_Group6#91]
**Describe the bug**
When I want to use this mar helper to find the route from "Kowloon Tong" to "Kowloon Bay", I saw some red lines in the screen showing me all stations I need to follow, but what happened is that when I want to resize this app window to make it bigger, all those highlighting red lines are gone and the whole layout was changed totally, I clicked the "Find Path" button again, but nothing happened, and red lines are still gone, 

please help to follow up.

**Possible related components**
Reference: Source/MetroSystem/src/userInterface, probably is main frame or Map.java which is responsible for the whole map display.

**To Reproduce**
1. Download your latest version after "Pull Request Preparation for new fully functional release #78"
2. Go to your main.class inside userInterface package
3. run Main function
4. select randomly 2 stations
5. click "find path" button
6. you may see there is no result path highlighting and the whole layout changes totally

**Expected behavior**
The result path should be highlighted using red lines.

**Screenshots**
<img width="1792" alt="截屏2021-11-13 下午5 05 26" src="https://user-images.githubusercontent.com/56904547/141613505-ed4e0679-cebc-41e3-87d1-6f1ea8c51958.png">
<img width="1781" alt="截屏2021-11-13 下午5 12 30" src="https://user-images.githubusercontent.com/56904547/141613524-9dd53d86-c095-4d60-ae9c-3c62e4878104.png">

**Environment**
 - OS: iOS
 - IDE: IntelliJ IDEA, Eclipse IDE
 - Version: release #78
 - JDK/JRE version JDK-11

**Additional context**
Maybe it would be better to fix the layout. Changing the position of different components every time clicking "find path" button makes the whole program hard to use.

**Comment by Daisy-127** [comment]
The program window will repaint every time when the panel is refreshed. After the showResult function is executed, the paint function is called again because of the change in position, therefore,  the highlighted line is gone.
