### ISSUE TITLE
The MTR helper cannot calculate and give me correct shortest path, or at least it cannot be displayed in the screen  

### ISSUE THREAD

**Issue by wliu283** [Alex-XJK/CS3343_Group6#92]
**Describe the bug**
I an year 1 student this year and just new to Shenzhen. MTR in Shenzhen is so complex so I want to use your MTR helper to find the shortest path. I just searched the path from Shenzhen University to Bo'an, but your program give me the shortest path from Linda to Honglang North. There must exists some bugs in your program. Please help to fix it.

**Possible related components**
Reference: MetroSystem/src/userInterface

**To Reproduce**
1. Download your latest version after "Pull Request Preparation for new fully functional release New released version #79"
2. Go to your main.class inside userInterface package
3. run Main function
4. select from Shenzhen University to Bo'an
5. click "find path" button
6. you may see the highlight path is from Linda to Honglang North

**Expected behavior**
The highlight path should be the shortest path from Shenzhen University to Bo'an

**Screenshots**
<img width="1792" alt="截屏2021-11-13 下午5 40 28" src="https://user-images.githubusercontent.com/56904547/141614213-bbeae873-8cf6-4611-9243-ad09bef7c713.png">

**Environment**
 - OS: iOS
 - IDE: IntelliJ IDEA, Eclipse IDE
 - Version New released version #79"
 - JDK/JRE version JDK-11

**Additional context**
To tell the truth, the UI of your program is pretty clear and easy to use.

**Comment by Daisy-127** [comment]
The background development data transmission does not subtract the total number of stations in Hong Kong
