### ISSUE TITLE
Unexpected long path under least time criteria

### ISSUE THREAD

**Issue by xz-cs** [Alex-XJK/CS3343_Group6#93]
**Describe the bug**
The behave is incorrect regarding the least time criteria.

**Possible related components**
Reference: path/package.class#method()

**To Reproduce**
1. Go to main frame
2. Choose least time criteria
3. Choose Central and Ocean Park
4. Click on Find Path, a very long path -- [Central, Hong Kong, Kowloon, Tsing Yi, Lai King, Nam Cheong, Austin, East Tsim Sha Tsui, Tsim Sha Tsui, Admiralty, Ocean Park] is shown.

**Expected behavior**
The path should be [Central, Admiralty, Ocean Park] instead of the long path.

**Screenshots**
<img width="1440" alt="Screenshot 2021-11-14 at 22 27 25" src="https://user-images.githubusercontent.com/59300821/141685360-1092c551-3787-4011-bcb9-d1c511351c75.png">

**Environment**
 - OS: macOS 12.0.1
 - IDE: IntelliJ IDEA
 - Version: Latest
 - JDK/JRE version: 17.0.1

**Additional context**

**Comment by Alex-XJK** [comment]
### CONFIRMED
The bug has been confirmed to be reproducible.  
Seems that there is something wrong with our Dijkstra Algorithm's detailed implementation, thank you for your information!

**Possible related components**
src/metroSystem.AlgDijkstra#findRoute(int, int, DataList)
